[package]
name = "rust-chart-wrker"
version = "0.1.0"
edition = "2021"
authors = [ "Kazuhiro Homma <kazu.homma@gmail.com>" ]

[package.metadata.release]
release = false

# https://github.com/rustwasm/wasm-pack/issues/1247
[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[lib]
crate-type = ["cdylib"]

[dependencies]
worker = { version="0.5.0", features=['http'] }
worker-macros = { version="0.5.0", features=['http'] }
console_error_panic_hook = "0.1.1"
http = "1.1"
plotters = "0.3.7"
image = "0.25.5"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
