name = "rust-chart-worker"
main = "build/worker/shim.mjs"
compatibility_date = "2024-12-17"

[build]
command = "cargo install -q worker-build && if [ \"$NODE_ENV\" = \"development\" ]; then worker-build --dev; else worker-build --release; fi"
